name: crimsonhttp
description: Dart Web Server inspired by sencha/connect
version: 0.0.1
authors:
- Chris Buckett <chrisbuckett@gmail.com>
- Adam Singer <financeCoding@gmail.com>
homepage: https://github.com/chrisbu/CrimsonHttp
dependencies:
  unittest:
    sdk: unittest
  log4dart: ">=1.0.0 <2.0.0"